# NumPy — Part 1
## Arrays, Indexing, Operations, and Basic Numerical Computing

**Level:** Beginner → Intermediate  
**Language:** English explanations + English Python code/comments  
**Library:** NumPy

---

### Notebook Goals

In this notebook, we will learn the most important NumPy fundamentals:

- What is NumPy and why do we use it?
- Creating one-dimensional and multidimensional arrays
- `ndim`, `shape`, `size`, `dtype`
- Indexing and Slicing
- Mathematical operations on arrays
- Element-wise operations and Matrix multiplication
- Statistical and mathematical functions
- `axis`
- Reshaping arrays
- Boolean indexing and `where`
- Combining, sorting, and modifying arrays
- Generating random data
- Data type conversion
- Saving and loading arrays

> **Note:** This notebook is designed to work both as a teaching handout and as a GitHub reference.

## 1. What is NumPy?

**NumPy (Numerical Python)** is one of the most important Python libraries for numerical computing.

NumPy provides a structure called **ndarray**, which is designed for storing and processing numerical arrays.

In real-world projects, NumPy is a foundation for many scientific tools and libraries, including:

- Data Science
- Machine Learning
- Deep Learning
- Image Processing
- Signal Processing
- Bioinformatics

### Why NumPy?

Python lists are useful, but NumPy is much better suited for numerical operations on large amounts of data.

One of NumPy's most important features is that many operations can be applied to an entire array without explicitly writing a `for` loop.

In [1]:
import numpy as np

print(np.__version__)

2.4.6


## 2. Importing NumPy

The standard way to import NumPy is:

```python
import numpy as np
```

`np` is simply the conventional short alias used to access NumPy.

For example:

```python
np.array()
np.mean()
np.zeros()
```

# 3. Creating Arrays with `np.array()`

The simplest way to create an array is to use `np.array()`.

In [2]:
# Create a one-dimensional NumPy array
numbers = np.array([10, 20, 30, 40, 50])

print(numbers)

[10 20 30 40 50]


### One-Dimensional Array (1D)

The following is a one-dimensional array:

```text
[10 20 30 40 50]
```

We can think of it as a **vector**.

In [3]:
# Create a two-dimensional NumPy array
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)

[[1 2 3]
 [4 5 6]]


### Two-Dimensional Array (2D)

This array contains:

- 2 rows
- 3 columns

```text
1  2  3
4  5  6
```

Two-dimensional arrays are commonly used to represent **matrices and tabular data**.

In [4]:
# Create a three-dimensional NumPy array
volume = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(volume)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Three-Dimensional Array (3D)

Three-dimensional arrays are important in areas such as image processing and medical imaging.

For example, a 3D MRI can be represented as a volumetric array:

```text
Height × Width × Depth
```

In Deep Learning, data may have even more dimensions, for example:

```text
Batch × Channel × Height × Width × Depth
```

# 4. Important ndarray Properties

Four important properties are:

| Property | Meaning |
|---|---|
| `ndim` | Number of dimensions |
| `shape` | Size of each dimension |
| `size` | Total number of elements |
| `dtype` | Data type |

In [5]:
# Inspect the main properties of an array
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("ndim :", a.ndim)
print("shape:", a.shape)
print("size :", a.size)
print("dtype:", a.dtype)

ndim : 2
shape: (2, 3)
size : 6
dtype: int64


### `ndim`

Returns the number of dimensions of the array.

```python
a.ndim
```

For a two-dimensional array:

```text
2
```

### `shape`

Describes the size of the array along each dimension.

```python
a.shape
```

For example:

```text
(2, 3)
```

This means:

```text
2 rows × 3 columns
```

### `size`

The total number of elements:

```python
a.size
```

در مثال بالا:

```text
2 × 3 = 6
```

### `dtype`

Shows the data type of the elements.

For example:

```text
int64
float64
float32
```

# 5. Creating Special Arrays

NumPy provides convenient functions for creating arrays filled with specific values.

In [6]:
# Create an array filled with zeros
zeros = np.zeros(5)

# Create an array filled with ones
ones = np.ones(5)

# Create an array filled with a constant value
full = np.full(5, 7)

print("zeros:", zeros)
print("ones :", ones)
print("full :", full)

zeros: [0. 0. 0. 0. 0.]
ones : [1. 1. 1. 1. 1.]
full : [7 7 7 7 7]


## `np.zeros()`

Creates an array whose elements are all zero:

```python
np.zeros(5)
```

For a two-dimensional array:

```python
np.zeros((3, 4))
```

---

## `np.ones()`

Creates an array whose elements are all one:

```python
np.ones(5)
```

---

## `np.full()`

Creates an array filled with a specified value:

```python
np.full((2, 3), 7)
```

In [7]:
# Create a 3x4 matrix of zeros
zeros_matrix = np.zeros((3, 4))

# Create a 2x3 matrix of ones
ones_matrix = np.ones((2, 3))

# Create a 2x2 matrix filled with 7
full_matrix = np.full((2, 2), 7)

print(zeros_matrix)
print()
print(ones_matrix)
print()
print(full_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[7 7]
 [7 7]]


## `np.eye()`

Creates an **identity matrix**:

```python
np.eye(3)
```

output:

```text
1 0 0
0 1 0
0 0 1
```

It is used in linear algebra and many scientific computations.

In [8]:
# Create a 3x3 identity matrix
identity = np.eye(3)

print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 6. `arange()` and `linspace()`

Two important functions for generating numerical sequences:

- `np.arange()`
- `np.linspace()`

In [9]:
# Create values using a fixed step
a = np.arange(0, 10, 2)

# Create a fixed number of evenly spaced values
b = np.linspace(0, 1, 5)

print("arange :", a)
print("linspace:", b)

arange : [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


### `np.arange(start, stop, step)`

Example:

```python
np.arange(0, 10, 2)
```

Result:

```text
[0 2 4 6 8]
```

Notice that `stop` is usually excluded.

### `np.linspace(start, stop, num)`

This function lets us specify the number of points.

```python
np.linspace(0, 1, 5)
```

Result:

```text
[0.   0.25 0.5  0.75 1.  ]
```

### Key Difference

```text
arange   → We specify the step size
linspace → We specify the number of points
```

# 7. Indexing — Accessing Elements

Like Python, NumPy uses zero-based indexing, so indexing starts at `0`.

In [10]:
# Create a one-dimensional array
a = np.array([10, 20, 30, 40, 50])

print("First element :", a[0])
print("Second element:", a[1])
print("Last element  :", a[-1])

First element : 10
Second element: 20
Last element  : 50


### Indexing in a Two-Dimensional Array

Syntax:

```python
array[row, column]
```

For example:

```python
a[0, 1]
```

This means:

```text
row = 0
column = 1
```

In [11]:
# Create a 2D array
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(matrix[0, 1])
print(matrix[2, 0])
print(matrix[-1, -1])

20
70
90


# 8. Slicing

General syntax:

```python
array[start:stop:step]
```

Example:

In [12]:
# Create an array
a = np.array([10, 20, 30, 40, 50, 60])

print(a[1:4])
print(a[:3])
print(a[2:])
print(a[::2])
print(a[::-1])

[20 30 40]
[10 20 30]
[30 40 50 60]
[10 30 50]
[60 50 40 30 20 10]


### Two-Dimensional Slicing

In a two-dimensional array, we can select both rows and columns.

```python
array[row, column]
```

For example:

```python
matrix[:, 1]
```

It means **all rows and column 1**.

In [13]:
# Create a 2D array
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Select the first row
print("First row:")
print(matrix[0, :])

# Select the second column
print("\nSecond column:")
print(matrix[:, 1])

# Select the first two columns
print("\nFirst two columns:")
print(matrix[:, :2])

First row:
[1 2 3]

Second column:
[2 5 8]

First two columns:
[[1 2]
 [4 5]
 [7 8]]


# 9. Modifying Elements

NumPy arrays are mutable.

We can directly change the value of an element.

In [14]:
# Create an array
a = np.array([10, 20, 30, 40])

# Change the third element
a[2] = 99

print(a)

[10 20 99 40]


# 10. Mathematical Operations on Arrays

One of NumPy's major advantages is that mathematical operations can be applied directly to arrays.

Suppose:

```python
a = [10, 20, 30]
```

We can write:

```python
a * 2
```

The operation is applied to all elements.

In [15]:
# Create an array
a = np.array([10, 20, 30])

print("a + 5 :", a + 5)
print("a - 5 :", a - 5)
print("a * 2 :", a * 2)
print("a / 2 :", a / 2)
print("a ** 2:", a ** 2)

a + 5 : [15 25 35]
a - 5 : [ 5 15 25]
a * 2 : [20 40 60]
a / 2 : [ 5. 10. 15.]
a ** 2: [100 400 900]


## Operations Between Two Arrays

When two arrays have compatible shapes, the following operations are performed **element-wise**.

In [16]:
# Create two arrays
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Addition       :", a + b)
print("Subtraction    :", a - b)
print("Multiplication :", a * b)
print("Division       :", a / b)
print("Power          :", a ** b)
print("Remainder      :", a % b)

Addition       : [12 24 35]
Subtraction    : [ 8 16 25]
Multiplication : [ 20  80 150]
Division       : [5. 5. 6.]
Power          : [     100   160000 24300000]
Remainder      : [0 0 0]


# 11. Difference Between `*` and `@`

This distinction is very important.

### `*` → Element-wise Multiplication

```python
A * B
```

Each element is multiplied by the corresponding element.

### `@` → Matrix Multiplication

```python
A @ B
```

Matrix multiplication is performed according to the rules of linear algebra.

In [17]:
# Create two matrices
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Element-wise multiplication:")
print(A * B)

print("\nMatrix multiplication:")
print(A @ B)

Element-wise multiplication:
[[ 5 12]
 [21 32]]

Matrix multiplication:
[[19 22]
 [43 50]]


### Manual Matrix Multiplication

For the top-left element:

```text
1×5 + 2×7 = 19
```

For the top-right element:

```text
1×6 + 2×8 = 22
```

For the second row:

```text
3×5 + 4×7 = 43
3×6 + 4×8 = 50
```

Therefore:

```text
[19 22]
[43 50]
```

### Dimension Rule

if

```text
A = m × n
B = n × p
```

then

```text
A @ B = m × p
```
The number of columns in the first matrix must be equal to the number of rows in the second matrix.

# 12. Broadcasting

Broadcasting allows NumPy to perform operations between arrays (or scalars) with compatible shapes.

For example:

In [18]:
# Broadcasting a scalar over an array
a = np.array([10, 20, 30, 40])

result = a + 5

print(result)

[15 25 35 45]


Conceptually, the value `5` is added to every element:

```text
[10, 20, 30, 40]
+
[ 5,  5,  5,  5]
=
[15, 25, 35, 45]
```

Broadcasting is an important concept in NumPy, Machine Learning, and Deep Learning.

# 13. Statistical Functions

NumPy provides many functions for numerical analysis.

In [19]:
# Create a sample dataset
data = np.array([10, 20, 30, 40, 50])

print("Sum     :", np.sum(data))
print("Mean    :", np.mean(data))
print("Median  :", np.median(data))
print("Std     :", np.std(data))
print("Variance:", np.var(data))
print("Minimum :", np.min(data))
print("Maximum :", np.max(data))

Sum     : 150
Mean    : 30.0
Median  : 30.0
Std     : 14.142135623730951
Variance: 200.0
Minimum : 10
Maximum : 50


## `argmin()` and `argmax()`

Key difference:

```python
np.max(a)
```

Returns the maximum value.

But:

```python
np.argmax(a)
```

**index** Returns the maximum value.

In [20]:
# Find the minimum and maximum values and their indices
a = np.array([10, 50, 20, 80, 30])

print("Maximum value :", np.max(a))
print("Maximum index :", np.argmax(a))

print("Minimum value :", np.min(a))
print("Minimum index :", np.argmin(a))

Maximum value : 80
Maximum index : 3
Minimum value : 10
Minimum index : 0


# 14. Important Mathematical Functions

Some commonly used functions:

- `np.sqrt()` → Square root
- `np.abs()` → Absolute value
- `np.power()` → Power
- `np.exp()` → Exponential function
- `np.log()` → Natural logarithm
- `np.log10()` → Base-10 logarithm

In [21]:
# Create an array
a = np.array([1, 4, 9, 16])

print("Square root:", np.sqrt(a))
print("Absolute   :", np.abs(a))
print("Power      :", np.power(a, 2))
print("Exponential:", np.exp(a))
print("Natural log:", np.log(a))
print("Log10      :", np.log10(a))

Square root: [1. 2. 3. 4.]
Absolute   : [ 1  4  9 16]
Power      : [  1  16  81 256]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Natural log: [0.         1.38629436 2.19722458 2.77258872]
Log10      : [0.         0.60205999 0.95424251 1.20411998]


# 15. `axis`

One of the most important NumPy concepts, especially when working with matrices and multidimensional data, is `axis`.

Suppose:

```text
1  2  3
4  5  6
```

If we write:

```python
np.sum(a)
```

All elements are summed.

But:

```python
np.sum(a, axis=0)
```

It returns the sum of each column.

و:

```python
np.sum(a, axis=1)
```

It returns the sum of each row.

In simple terms:

```text
axis=0 → result for each column
axis=1 → result for each row
```

In [22]:
# Create a 2D array
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Total:", np.sum(a))
print("Sum over axis=0:", np.sum(a, axis=0))
print("Sum over axis=1:", np.sum(a, axis=1))

Total: 21
Sum over axis=0: [5 7 9]
Sum over axis=1: [ 6 15]


The same concept applies to statistical functions:

```python
np.mean(a, axis=0)
np.mean(a, axis=1)

np.max(a, axis=0)
np.max(a, axis=1)
```

This concept is very important when working with tabular data and Machine Learning models.

In [23]:
# Calculate statistics along different axes
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Column means:", np.mean(a, axis=0))
print("Row means   :", np.mean(a, axis=1))

Column means: [25. 35. 45.]
Row means   : [20. 50.]


# 16. Reshaping with `reshape()`

`reshape()` changes the shape of an array without changing the number of elements.

In [24]:
# Create a one-dimensional array
a = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into 2 rows and 3 columns
matrix = a.reshape(2, 3)

print(matrix)
print("Shape:", matrix.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


### `reshape` Rule

The total number of elements must remain unchanged.
For example, if the array contains **12 elements**:
```text
12 = 2 × 6
12 = 3 × 4
12 = 1 × 12
```

So these are valid:

```python
a.reshape(2, 6)
a.reshape(3, 4)
a.reshape(1, 12)
```

But:

```python
a.reshape(5, 3)
```

This is not possible because:

```text
5 × 3 = 15
```

## Using `-1`

NumPy can infer one dimension automatically:

```python
a.reshape(2, -1)
```

If there are 6 elements, NumPy understands that the second dimension must be `3`.

In [25]:
# Let NumPy infer the second dimension
a = np.array([1, 2, 3, 4, 5, 6])

matrix = a.reshape(2, -1)

print(matrix)
print(matrix.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


# 17. `flatten()` and `ravel()`

Both can be used to convert a multidimensional array into a one-dimensional array.

In [26]:
# Create a 2D array
a = np.array([
    [1, 2],
    [3, 4]
])

flat = a.flatten()
raveled = a.ravel()

print("flatten:", flat)
print("ravel  :", raveled)

flatten: [1 2 3 4]
ravel  : [1 2 3 4]


In simple terms:

```text
flatten → usually creates an independent copy of the data
ravel   → returns a view of the data whenever possible
```
the most important thing to remember is that **both convert an array into a 1D array**.

# 18. Transpose

Transpose swaps rows and columns.

In [27]:
# Create a matrix
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original:")
print(a)

print("\nTranspose:")
print(a.T)

Original:
[[1 2 3]
 [4 5 6]]

Transpose:
[[1 4]
 [2 5]
 [3 6]]


For example:

```text
Original:

1 2 3
4 5 6

Transpose:

1 4
2 5
3 6
```

For two-dimensional arrays, `a.T` is a common shorthand for transpose.

# 19. Boolean Indexing

We can select part of an array based on a condition.

In [28]:
# Create an array
a = np.array([10, 20, 30, 40, 50])

# Create a Boolean condition
condition = a > 25

print("Condition:", condition)
print("Filtered :", a[condition])

Condition: [False False  True  True  True]
Filtered : [30 40 50]


We can also write the condition directly:

```python
a[a > 25]
```

This technique is widely used in Data Science.

In [29]:
# Select values greater than 25
a = np.array([10, 20, 30, 40, 50])

print(a[a > 25])

[30 40 50]


## Combining Multiple Conditions

For NumPy conditions, we use:

```text
&  → AND
|  → OR
~  → NOT
```

operators.

It is good practice to wrap each condition in parentheses.

In [30]:
# Create an array
a = np.array([10, 20, 30, 40, 50])

# Select values between 20 and 40
result = a[(a >= 20) & (a <= 40)]

print(result)

[20 30 40]


# 20. `np.where()`

`where()` is useful for finding positions that satisfy a condition or creating conditional outputs.

In [31]:
# Create an array
a = np.array([10, 20, 30, 40, 50])

# Find indices where the condition is true
indices = np.where(a > 25)

print(indices)

(array([2, 3, 4]),)


We can also use the three-argument form of `where`:

```python
np.where(condition, value_if_true, value_if_false)
```

In [32]:
# Replace values greater than 25 with 1, otherwise use 0
a = np.array([10, 20, 30, 40, 50])

result = np.where(a > 25, 1, 0)

print(result)

[0 0 1 1 1]


# 21. `nonzero()` and `unique()`

### `np.nonzero()`

Finds the indices of non-zero elements.

In [33]:
# Find non-zero element indices
a = np.array([0, 5, 0, 8, 3])

print(np.nonzero(a))

(array([1, 3, 4]),)


### `np.unique()`

Returns the unique values in an array.

In [34]:
# Find unique values
a = np.array([1, 2, 2, 3, 3, 3, 4])

print(np.unique(a))

[1 2 3 4]


With `return_counts=True`, we can also get the frequency of each unique value.

In [35]:
# Count the frequency of each unique value
a = np.array([1, 2, 2, 3, 3, 3, 4])

values, counts = np.unique(a, return_counts=True)

print("Values:", values)
print("Counts:", counts)

Values: [1 2 3 4]
Counts: [1 2 3 1]


# 22. Sorting

Two important methods:

```python
np.sort(a)
a.sort()
```

Main difference:

- `np.sort(a)` → returns a sorted array.
- `a.sort()` → sorts the original array in-place.

In [36]:
# Create an unsorted array
a = np.array([40, 10, 30, 20])

sorted_a = np.sort(a)

print("Original:", a)
print("Sorted  :", sorted_a)

# Sort the original array in-place
a.sort()

print("After a.sort():", a)

Original: [40 10 30 20]
Sorted  : [10 20 30 40]
After a.sort(): [10 20 30 40]


# 23. Combining Arrays

Important functions:

- `np.concatenate()`
- `np.vstack()`
- `np.hstack()`

In [37]:
# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("concatenate:", np.concatenate([a, b]))
print("hstack     :", np.hstack([a, b]))

concatenate: [1 2 3 4 5 6]
hstack     : [1 2 3 4 5 6]


In [38]:
# Create two row vectors
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])

print("vstack:")
print(np.vstack([a, b]))

print("\nhstack:")
print(np.hstack([a, b]))

vstack:
[[1 2 3]
 [4 5 6]]

hstack:
[[1 2 3 4 5 6]]


### Simple Idea

```text
vstack → Vertical Stack → stack arrays on top of each other
hstack → Horizontal Stack → place arrays side by side
```

# 24. `append()`, `insert()`, `delete()`

These functions can be used to create a new array by appending, inserting, or deleting elements.

In [39]:
# Create an array
a = np.array([10, 20, 30])

print("Append:", np.append(a, 40))
print("Insert:", np.insert(a, 1, 99))
print("Delete:", np.delete(a, 1))

# The original array is unchanged
print("Original:", a)

Append: [10 20 30 40]
Insert: [10 99 20 30]
Delete: [10 30]
Original: [10 20 30]


> **Note:** Unlike `list.append()`, `np.append()` usually creates a new array rather than growing the original array in-place.

# 25. Random — Generating Random Data

NumPy provides several tools for generating random data.

These tools are useful for:

- Creating synthetic datasets
- Simulation
- Algorithm testing
- Machine Learning
- Statistical Modeling

کاربرد دارند.

In [40]:
# Generate random floating-point values between 0 and 1
print(np.random.rand(5))

# Generate random integers
print(np.random.randint(0, 10, size=5))

# Generate samples from a normal distribution
print(np.random.normal(0, 1, size=5))

# Randomly choose elements from an array
a = np.array([10, 20, 30, 40, 50])
print(np.random.choice(a, size=3))

[0.60300424 0.67915065 0.45655017 0.95186915 0.97161465]
[1 7 9 3 0]
[-1.7160101  -1.07225677 -0.47974808  0.28112817  0.35762737]
[20 20 40]


## `np.random.seed()`

If we want random results to be reproducible across runs, we can set a seed.

In [41]:
# Set a fixed random seed for reproducibility
np.random.seed(42)

print(np.random.randint(0, 100, size=5))

[51 92 14 71 60]


# 26. Data Types and `astype()`

NumPy manages the data type of array elements.

For example:

```text
int32
int64
float32
float64
bool
```

We can convert the data type.

In [42]:
# Create an integer array
a = np.array([1, 2, 3, 4])

print("Original dtype:", a.dtype)

# Convert the array to float32
b = a.astype(np.float32)

print("New dtype     :", b.dtype)
print("Array          :", b)

Original dtype: int64
New dtype     : float32
Array          : [1. 2. 3. 4.]


### Why is `float32` important?

In Machine Learning and Deep Learning, `float32` is very common because it uses less memory than `float64` and is usually sufficient for many model computations.

For example:

```python
X = X.astype(np.float32)
```

# 27. Saving and Loading Arrays

NumPy provides dedicated formats for saving arrays.

### `np.save()`

Saves a single array to a `.npy` file.

In [43]:
# Create sample data
a = np.array([10, 20, 30, 40, 50])

# Save the array
np.save("sample_array.npy", a)

# Load the array
loaded = np.load("sample_array.npy")

print(loaded)

[10 20 30 40 50]


### `np.savez()`

Saves multiple arrays in a single `.npz` file.

In [44]:
# Create two arrays
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

# Save multiple arrays
np.savez("sample_data.npz", x=x, y=y)

# Load the data
data = np.load("sample_data.npz")

print("x:", data["x"])
print("y:", data["y"])

x: [1 2 3]
y: [10 20 30]


# 28. Practical Example: Patient Data

Now we combine the main concepts in a simple biological example.

Suppose we have the following data:

```text
Age
Tumor Volume
IDH1
```

Example:

- `Age` → Patient age
- `Tumor Volume` → Tumor volume
- `IDH1` → Encoded IDH1 status

> These values are for educational purposes only and are not real patient data.

In [45]:
# Create a small synthetic clinical dataset
patients = np.array([
    [65, 120, 1],
    [52,  80, 0],
    [71, 150, 1],
    [45,  60, 0],
    [60, 100, 1]
])

print(patients)
print("Shape:", patients.shape)

[[ 65 120   1]
 [ 52  80   0]
 [ 71 150   1]
 [ 45  60   0]
 [ 60 100   1]]
Shape: (5, 3)


## Selecting Columns

To select the first column:

```python
patients[:, 0]
```

For the second column:

```python
patients[:, 1]
```

In [46]:
# Extract individual features
ages = patients[:, 0]
tumor_volume = patients[:, 1]
idh1 = patients[:, 2]

print("Ages:", ages)
print("Tumor volume:", tumor_volume)
print("IDH1:", idh1)

Ages: [65 52 71 45 60]
Tumor volume: [120  80 150  60 100]
IDH1: [1 0 1 0 1]


## Calculating Statistics

In [47]:
# Calculate basic statistics
print("Mean age:", np.mean(ages))
print("Maximum tumor volume:", np.max(tumor_volume))
print("Minimum tumor volume:", np.min(tumor_volume))
print("Mean tumor volume:", np.mean(tumor_volume))

Mean age: 58.6
Maximum tumor volume: 150
Minimum tumor volume: 60
Mean tumor volume: 102.0


## Filtering Patients

For example, patients older than 60:

In [48]:
# Select patients older than 60 years
older_patients = patients[patients[:, 0] > 60]

print(older_patients)

[[ 65 120   1]
 [ 71 150   1]]


## Patient with the Largest Tumor Volume

First, find the index of the largest tumor volume.

In [49]:
# Find the patient with the largest tumor volume
index = np.argmax(patients[:, 1])

print("Patient index:", index)
print("Patient data :", patients[index])

Patient index: 2
Patient data : [ 71 150   1]


# 29. Simple Normalization

A common operation in Machine Learning is scaling data.

One simple method is:

```text
z = (x - mean) / std
```

In this example, we apply it to age.

In [50]:
# Standardize age values using z-score normalization
ages = patients[:, 0].astype(np.float64)

mean_age = np.mean(ages)
std_age = np.std(ages)

normalized_ages = (ages - mean_age) / std_age

print("Original ages   :", ages)
print("Normalized ages :", normalized_ages)

Original ages   : [65. 52. 71. 45. 60.]
Normalized ages : [ 0.69401419 -0.71570213  1.34465249 -1.47478015  0.1518156 ]


# 30. Summary of Important Functions

## Array Creation

```python
np.array()
np.zeros()
np.ones()
np.full()
np.eye()
np.arange()
np.linspace()
```

## Properties

```python
a.ndim
a.shape
a.size
a.dtype
```

## Indexing and Slicing

```python
a[0]
a[-1]
a[1:4]
a[:, 0]
a[condition]
```

## Reshaping

```python
a.reshape()
a.flatten()
a.ravel()
a.T
```

## Statistics

```python
np.sum()
np.mean()
np.median()
np.std()
np.var()
np.min()
np.max()
np.argmin()
np.argmax()
```

## Mathematical Functions

```python
np.sqrt()
np.abs()
np.power()
np.exp()
np.log()
np.log10()
```

## Conditions and Search

```python
np.where()
np.nonzero()
np.unique()
```

## Combining

```python
np.concatenate()
np.vstack()
np.hstack()
```

## Modification

```python
np.append()
np.insert()
np.delete()
```

## Sorting

```python
np.sort()
a.sort()
```

## Random

```python
np.random.rand()
np.random.randint()
np.random.normal()
np.random.choice()
np.random.seed()
```

## Data Type

```python
a.astype()
```

## Saving

```python
np.save()
np.load()
np.savez()
```

# 31. NumPy Golden Rules

### 1. Always check `shape`

```python
print(X.shape)
```

Many array-related errors are caused by incorrect dimensions.

### 2. Do not forget the difference between `*` and `@`

```python
A * B   # Element-wise multiplication
A @ B   # Matrix multiplication
```

### 3. Learn `axis` well

```python
axis=0   # Operation across rows → result for columns
axis=1   # Operation across columns → result for rows
```

### 4. Boolean indexing is very important

```python
a[a > 10]
```

### 5. `reshape()` does not change the number of elements

```python
a.reshape(...)
```
It only changes the **shape of the data**.

### 6. NumPy is for numerical computing

When we move to Pandas, Scikit-learn, PyTorch, and Bioinformatics projects, we will constantly work with NumPy arrays and similar structures.

# 32. Exercises

## Exercise 1 — Array Creation

Create an array containing numbers from 10 to 100 with a step of 10.

---

## Exercise 2 — Shape

Create a 3×4 array and print:

- `ndim`
- `shape`
- `size`
- `dtype`

---

## Exercise 3 — Indexing

For the following array:

```python
a = np.array([5, 10, 15, 20, 25, 30])
```

Find the following:

1. The first element
2. The last element
3. The first three elements
4. Elements at even indices

---

## Exercise 4 — Matrix

Create the following matrix:

```text
1 2 3
4 5 6
7 8 9
```

سTherefore:

- Select the element `5`.
- Select the second column.
- Select the third row.
- Select the first two columns.

---

## Exercise 5 — Statistics

For the following array:

```python
a = np.array([12, 18, 25, 31, 42, 50])
```

Calculate:

- Mean
- Median
- Standard deviation
- Minimum
- Maximum
- Index of maximum

---

## Exercise 6 — Filtering

Select all numbers greater than 30.

---

## Exercise 7 — Matrix Multiplication

Create two compatible matrices and calculate `A @ B`.

---

## Exercise 8 — Biological Application

Create a 10×3 array representing the following three features for 10 patients:

```text
Age
Tumor Volume
IDH1
```

1. Calculate the mean age.
2. Find the maximum tumor volume.
3. Find the patient with the maximum tumor volume.
4. Filter patients older than 60.
5. Check the array data type.

# 33. Cheat Sheet

| Category | Function / Attribute | کاربرد |
|---|---|---|
| Creation | `np.array()` | ساخت آرایه |
| Creation | `np.zeros()` | آرایه صفر |
| Creation | `np.ones()` | آرایه یک |
| Creation | `np.full()` | مقدار ثابت |
| Creation | `np.eye()` | ماتریس همانی |
| Creation | `np.arange()` | دنباله با step |
| Creation | `np.linspace()` | دنباله با تعداد مشخص |
| Properties | `a.ndim` | تعداد ابعاد |
| Properties | `a.shape` | شکل آرایه |
| Properties | `a.size` | تعداد عناصر |
| Properties | `a.dtype` | نوع داده |
| Reshape | `a.reshape()` | تغییر شکل |
| Reshape | `a.flatten()` | تبدیل به 1D |
| Reshape | `a.ravel()` | تبدیل به 1D |
| Reshape | `a.T` | Transpose |
| Statistics | `np.sum()` | مجموع |
| Statistics | `np.mean()` | میانگین |
| Statistics | `np.median()` | میانه |
| Statistics | `np.std()` | انحراف معیار |
| Statistics | `np.var()` | واریانس |
| Statistics | `np.min()` | کمینه |
| Statistics | `np.max()` | بیشینه |
| Statistics | `np.argmin()` | index کمینه |
| Statistics | `np.argmax()` | index بیشینه |
| Math | `np.sqrt()` | جذر |
| Math | `np.abs()` | قدرمطلق |
| Math | `np.power()` | توان |
| Math | `np.exp()` | نمایی |
| Math | `np.log()` | لگاریتم طبیعی |
| Math | `np.log10()` | لگاریتم پایه 10 |
| Search | `np.where()` | شرط |
| Search | `np.nonzero()` | عناصر غیرصفر |
| Search | `np.unique()` | مقادیر یکتا |
| Combine | `np.concatenate()` | اتصال |
| Combine | `np.vstack()` | اتصال عمودی |
| Combine | `np.hstack()` | اتصال افقی |
| Modify | `np.append()` | اضافه کردن |
| Modify | `np.insert()` | درج |
| Modify | `np.delete()` | حذف |
| Sorting | `np.sort()` | مرتب‌سازی |
| Sorting | `a.sort()` | مرتب‌سازی درجا |
| Random | `np.random.rand()` | اعداد تصادفی 0 تا 1 |
| Random | `np.random.randint()` | اعداد صحیح تصادفی |
| Random | `np.random.normal()` | توزیع نرمال |
| Random | `np.random.choice()` | انتخاب تصادفی |
| Random | `np.random.seed()` | تکرارپذیری |
| Data Type | `a.astype()` | تبدیل نوع داده |
| Saving | `np.save()` | ذخیره‌ی یک آرایه |
| Saving | `np.load()` | بارگذاری |
| Saving | `np.savez()` | ذخیره‌ی چند آرایه |

# End of Part 1

In this notebook, we covered the core concepts of working with NumPy arrays.

In the next part, we can move into more advanced topics, such as:

- Advanced Indexing
- Advanced Broadcasting
- Vectorization
- Linear Algebra
- Matrix operations
- Random distributions
- Memory and Views vs Copies
- Performance
- Working with multidimensional data
- Connecting NumPy to Pandas and Scikit-learn
- More realistic Bioinformatics examples

**Next → NumPy Part 2**