# NumPy — Part 2
## Advanced Array Manipulation, Vectorization, Broadcasting & Linear Algebra

**Level:** Beginner → Intermediate → Advanced


This notebook builds on **NumPy Part 1** and serves as a continuation of the fundamental concepts covered there. It focuses on more advanced topics that are especially important in **Machine Learning, Deep Learning, Statistics, and Bioinformatics**.


### Learning Goals

- Advanced indexing and slicing
- `axis` in depth
- Broadcasting
- Vectorization
- Copy vs View
- Shape manipulation
- Stacking and splitting
- Missing and special values
- Mathematical foundations of linear algebra
- Random number generation
- Data normalization
- Performance and memory
- Practical Bioinformatics and Machine Learning examples
- Exercises and a compact cheat sheet


## 1. Quick Review

A NumPy `ndarray` is a multidimensional numerical data structure.

```text
1D → Vector
2D → Matrix
3D+ → Multidimensional array
```

Important properties:

```python
a.ndim
a.shape
a.size
a.dtype
```

Part 1 introduced the basics. Part 2 focuses on deeper concepts and more realistic numerical workflows.


## 2. Advanced Indexing

NumPy supports:

- Basic indexing
- Slicing
- Integer/fancy indexing
- Boolean indexing

Advanced indexing is useful when selecting particular samples, features, rows, or columns.


In [1]:
import numpy as np

a = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print(a)

# Select rows 0 and 2
print("\nRows 0 and 2:")
print(a[[0, 2]])

# Select columns 1 and 3
print("\nColumns 1 and 3:")
print(a[:, [1, 3]])

# Select a[0, 1] and a[2, 3]
print("\nSelected elements:")
print(a[[0, 2], [1, 3]])


[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Rows 0 and 2:
[[ 10  20  30  40]
 [ 90 100 110 120]]

Columns 1 and 3:
[[ 20  40]
 [ 60  80]
 [100 120]]

Selected elements:
[ 20 120]


## 3. Boolean Indexing

Boolean indexing selects elements using a condition.

For example:

```python
a > 50
```

creates a Boolean mask.

For multiple conditions:

```text
& → AND
| → OR
~ → NOT
```

Use parentheses around individual conditions.


In [2]:
x = np.array([10, 20, 30, 40, 50])

mask = x > 30

print("Mask:", mask)
print("Filtered values:", x[mask])

result = x[(x > 20) & (x < 50)]

print("Between 20 and 50:", result)


Mask: [False False False  True  True]
Filtered values: [40 50]
Between 20 and 50: [30 40]


## 4. Advanced Slicing

General syntax:

```text
array[start:stop:step]
```

Examples:

```text
a[::2]  → every second element
a[::-1] → reverse the array
a[:, 1] → all rows and column 1
```

For a 2D array:

```text
a[rows, columns]
```


In [3]:
a = np.arange(1, 13).reshape(3, 4)

print("Array:")
print(a)

print("\nAll rows and column 1:")
print(a[:, 1])

print("\nFirst two columns:")
print(a[:, :2])

print("\nReverse every row:")
print(a[:, ::-1])


Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

All rows and column 1:
[ 2  6 10]

First two columns:
[[ 1  2]
 [ 5  6]
 [ 9 10]]

Reverse every row:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


## 5. Axis — Deep Understanding

For a 2D array:

```text
axis=0 → result for each column
axis=1 → result for each row
```

Another mental model:

```text
axis=0 → collapse the rows
axis=1 → collapse the columns
```

### Bioinformatics Example

If:

```text
rows    = patients
columns = genes
```

and:

```python
expression.shape == (100, 5000)
```

then:

```python
expression.mean(axis=0)
```

calculates the mean expression of each gene across patients.

And:

```python
expression.mean(axis=1)
```

calculates the mean expression of each patient across genes.


In [4]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Sum for each column:", np.sum(a, axis=0))
print("Sum for each row:", np.sum(a, axis=1))

print("Mean for each column:", np.mean(a, axis=0))
print("Mean for each row:", np.mean(a, axis=1))


Sum for each column: [5 7 9]
Sum for each row: [ 6 15]
Mean for each column: [2.5 3.5 4.5]
Mean for each row: [2. 5.]


## 6. Broadcasting

Broadcasting allows NumPy to perform operations between arrays with compatible shapes without manually copying data.

NumPy compares shapes from **right to left**.

Two dimensions are compatible when:

1. They are equal, or
2. One of them is `1`.

Example:

```text
A.shape = (3, 4)
b.shape = (4,)
```

The vector can be broadcast across all rows.


In [5]:
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

b = np.array([10, 20, 30, 40])

print(A + b)


[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


### Broadcasting with a Column Vector

A column vector with shape `(3, 1)` can be broadcast across a `(3, 4)` matrix.


In [6]:
A = np.arange(1, 13).reshape(3, 4)
column = np.array([[10], [20], [30]])

print("A:")
print(A)

print("\nColumn vector:")
print(column)

print("\nBroadcasted result:")
print(A + column)


A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Column vector:
[[10]
 [20]
 [30]]

Broadcasted result:
[[11 12 13 14]
 [25 26 27 28]
 [39 40 41 42]]


### Broadcasting Error

If:

```text
A.shape = (3, 4)
b.shape = (3,)
```

the shapes are not directly compatible because the rightmost dimensions are:

```text
4 ≠ 3
```

When broadcasting fails, inspect the shapes first:

```python
A.shape
b.shape
```


In [7]:
A = np.zeros((3, 4))
b = np.zeros(3)

print("A shape:", A.shape)
print("b shape:", b.shape)

# The next operation would raise a broadcasting error:
# print(A + b)


A shape: (3, 4)
b shape: (3,)


## 7. Vectorization

**Vectorization** means applying operations to whole arrays rather than processing elements one by one with explicit Python loops.

Instead of:

```python
result = []
for x in data:
    result.append(x * 2)
```

we can write:

```python
result = data * 2
```

Vectorization usually produces cleaner code and can be much faster for numerical workloads.


In [8]:
data = np.arange(1, 1_000_001)

# Vectorized operation
result = data * 2

print("First 10 values:", result[:10])


First 10 values: [ 2  4  6  8 10 12 14 16 18 20]


## 8. Copy vs View

This distinction is essential.

```text
b = a       → another reference to the same array
a.copy()    → independent copy
a.view()    → view sharing the underlying data
```

Use `np.shares_memory()` to check whether arrays share memory.


In [9]:
a = np.array([1, 2, 3])

b = a
c = a.copy()
d = a.view()

a[0] = 100

print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)

print("\nMemory sharing:")
print("a and b:", np.shares_memory(a, b))
print("a and c:", np.shares_memory(a, c))
print("a and d:", np.shares_memory(a, d))


a: [100   2   3]
b: [100   2   3]
c: [1 2 3]
d: [100   2   3]

Memory sharing:
a and b: True
a and c: False
a and d: True


## 9. Shape Manipulation

Important tools:

```text
reshape()
flatten()
ravel()
resize()
expand_dims()
squeeze()
transpose()
swapaxes()
moveaxis()
```

These operations are particularly useful when preparing data for Machine Learning and Deep Learning models.


In [10]:
a = np.arange(1, 7).reshape(2, 3)

print("Original:")
print(a)

print("\nReshape to (3, 2):")
print(a.reshape(3, 2))

print("\nFlatten:")
print(a.flatten())

print("\nRavel:")
print(a.ravel())

print("\nTranspose:")
print(a.T)


Original:
[[1 2 3]
 [4 5 6]]

Reshape to (3, 2):
[[1 2]
 [3 4]
 [5 6]]

Flatten:
[1 2 3 4 5 6]

Ravel:
[1 2 3 4 5 6]

Transpose:
[[1 4]
 [2 5]
 [3 6]]


In [11]:
x = np.array([1, 2, 3])

expanded = np.expand_dims(x, axis=0)

print("Original shape:", x.shape)
print("Expanded shape:", expanded.shape)

squeezed = np.squeeze(expanded)

print("Squeezed shape:", squeezed.shape)


Original shape: (3,)
Expanded shape: (1, 3)
Squeezed shape: (3,)


## 10. Stacking and Splitting

### Combining

```text
concatenate() → join along an existing axis
stack()       → join along a new axis
vstack()      → vertical stacking
hstack()      → horizontal stacking
```

### Splitting

```text
split()
array_split()
vsplit()
hsplit()
```


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("concatenate:", np.concatenate([a, b]))

print("\nstack:")
print(np.stack([a, b]))

print("\nvstack:")
print(np.vstack([a, b]))

print("\nhstack:")
print(np.hstack([a, b]))


concatenate: [1 2 3 4 5 6]

stack:
[[1 2 3]
 [4 5 6]]

vstack:
[[1 2 3]
 [4 5 6]]

hstack:
[1 2 3 4 5 6]


In [13]:
x = np.arange(12)

parts = np.split(x, 3)

for i, part in enumerate(parts, start=1):
    print(f"Part {i}:", part)


Part 1: [0 1 2 3]
Part 2: [4 5 6 7]
Part 3: [ 8  9 10 11]


## 11. Missing and Special Values

Scientific datasets may contain:

```text
NaN   → Not a Number
inf   → positive infinity
-inf  → negative infinity
```

Useful checks:

```python
np.isnan()
np.isinf()
np.isfinite()
```

NaN-aware statistics include:

```python
np.nanmean()
np.nanmedian()
np.nanstd()
np.nansum()
```


In [14]:
x = np.array([10, 20, np.nan, np.inf, 50])

print("NaN mask:", np.isnan(x))
print("Inf mask:", np.isinf(x))
print("Finite mask:", np.isfinite(x))

print("nanmean:", np.nanmean(x))


NaN mask: [False False  True False False]
Inf mask: [False False False  True False]
Finite mask: [ True  True False False  True]
nanmean: inf


## 12. Mathematical Functions

NumPy provides vectorized mathematical functions such as:

```text
np.sqrt()
np.abs()
np.power()
np.exp()
np.log()
np.log10()
np.sin()
np.cos()
```

For example:

$$
\sqrt{x}
$$

is implemented with:

```python
np.sqrt(x)
```


In [15]:
x = np.array([1, 4, 9, 16])

print("sqrt:", np.sqrt(x))
print("power:", np.power(x, 2))
print("log:", np.log(x))
print("log10:", np.log10(x))


sqrt: [1. 2. 3. 4.]
power: [  1  16  81 256]
log: [0.         1.38629436 2.19722458 2.77258872]
log10: [0.         0.60205999 0.95424251 1.20411998]


# 13. Linear Algebra

Linear algebra is fundamental to:

- Machine Learning
- Deep Learning
- Statistics
- Computer Vision
- Bioinformatics

Core concepts:

```text
Scalars
Vectors
Matrices
Dot products
Matrix multiplication
Transpose
Norms
Determinants
Inverse matrices
Eigenvalues
Eigenvectors
```


## Scalars, Vectors, and Matrices

A **scalar** is a single number:

$$
x = 5
$$

A **vector** is an ordered collection:

$$
x =
\begin{bmatrix}
1\\
2\\
3
\end{bmatrix}
$$

A **matrix** is a rectangular arrangement of values:

$$
A =
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}
$$


## 14. Dot Product

For two vectors:

$$
a = [a_1,a_2,\dots,a_n]
$$

and:

$$
b = [b_1,b_2,\dots,b_n]
$$

the dot product is:

$$
a \cdot b = \sum_{i=1}^{n} a_i b_i
$$

Example:

$$
[1,2,3]\cdot[4,5,6]
= 1(4)+2(5)+3(6)
= 32
$$

In NumPy:

```python
np.dot(a, b)
```


In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Dot product:", np.dot(a, b))
print("Using @:", a @ b)


Dot product: 32
Using @: 32


## 15. Matrix Multiplication

If:

$$
A = m \times n
$$

and:

$$
B = n \times p
$$

then:

$$
A @ B = m \times p
$$

The number of columns in the first matrix must equal the number of rows in the second matrix.

For each element:

$$
C_{ij}=\sum_k A_{ik}B_{kj}
$$

### Important distinction

```text
A * B → element-wise multiplication
A @ B → matrix multiplication
```


In [17]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Element-wise multiplication:")
print(A * B)

print("\nMatrix multiplication:")
print(A @ B)


Element-wise multiplication:
[[ 5 12]
 [21 32]]

Matrix multiplication:
[[19 22]
 [43 50]]


## 16. Determinant, Inverse, and Linear Systems

For a 2×2 matrix:

$$
A =
\begin{bmatrix}
a & b\\
c & d
\end{bmatrix}
$$

the determinant is:

$$
\det(A)=ad-bc
$$

Use:

```python
np.linalg.det(A)
```

For a linear system:

$$
Ax=b
$$

use:

```python
np.linalg.solve(A, b)
```

This is generally preferable to explicitly computing an inverse for solving a system.


In [18]:
A = np.array([
    [3, 1],
    [1, 2]
], dtype=float)

b = np.array([9, 8], dtype=float)

print("Determinant:", np.linalg.det(A))

solution = np.linalg.solve(A, b)

print("Solution:", solution)
print("Check A @ x:", A @ solution)


Determinant: 5.000000000000001
Solution: [2. 3.]
Check A @ x: [9. 8.]


## 17. Eigenvalues and Eigenvectors

An eigenvector satisfies:

$$
Av = \lambda v
$$

where:

- `v` is an eigenvector
- `λ` is the corresponding eigenvalue

In NumPy:

```python
values, vectors = np.linalg.eig(A)
```

Eigenvalues and eigenvectors are important in dimensionality reduction and methods such as PCA.


In [19]:
A = np.array([
    [2, 0],
    [0, 3]
], dtype=float)

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[2. 3.]

Eigenvectors:
[[1. 0.]
 [0. 1.]]


## 18. Vector Norm

The Euclidean (L2) norm is:

$$
\|x\|_2 = \sqrt{\sum_i x_i^2}
$$

For:

$$
x=[3,4]
$$

we get:

$$
\sqrt{3^2+4^2}=5
$$

In NumPy:

```python
np.linalg.norm(x)
```


In [20]:
x = np.array([3, 4])

print("L2 norm:", np.linalg.norm(x))


L2 norm: 5.0


# 19. Random Numbers and Simulation

Random numbers are useful for:

- simulations
- testing
- synthetic datasets
- statistical experiments
- Machine Learning

A modern approach is:

```python
rng = np.random.default_rng(seed)
```

Using a fixed seed makes results reproducible.


In [21]:
rng = np.random.default_rng(42)

print("Random floats:", rng.random(5))
print("Random integers:", rng.integers(1, 10, size=5))
print("Normal samples:", rng.normal(loc=0, scale=1, size=5))


Random floats: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Random integers: [5 9 7 7 7]
Normal samples: [-0.01680116 -0.85304393  0.87939797  0.77779194  0.0660307 ]


## 20. Data Normalization

### Min-Max Scaling

$$
x'=
\frac{x-x_{min}}
{x_{max}-x_{min}}
$$

This scales values approximately to `[0, 1]`.

### Z-Score Standardization

$$
z=
\frac{x-\mu}{\sigma}
$$

where:

- `μ` = mean
- `σ` = standard deviation


In [22]:
x = np.array([10, 20, 30, 40, 50], dtype=float)

min_max = (x - x.min()) / (x.max() - x.min())
z_score = (x - x.mean()) / x.std()

print("Original:", x)
print("Min-Max:", min_max)
print("Z-score:", z_score)


Original: [10. 20. 30. 40. 50.]
Min-Max: [0.   0.25 0.5  0.75 1.  ]
Z-score: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


## 21. Feature Scaling with Broadcasting

Suppose:

```text
Rows    → samples
Columns → features
```

and:

```python
X.shape == (500, 20)
```

Calculate one mean and one standard deviation per feature:

```python
mean = X.mean(axis=0)
std = X.std(axis=0)
```

Then broadcasting allows:

```python
X_scaled = (X - mean) / std
```

This combines three major NumPy concepts:

```text
axis + broadcasting + vectorization
```


In [23]:
rng = np.random.default_rng(42)

X = rng.normal(size=(500, 20))

mean = X.mean(axis=0)
std = X.std(axis=0)

# Protect against division by zero for constant features
std_safe = np.where(std == 0, 1, std)

X_scaled = (X - mean) / std_safe

print("X shape:", X.shape)
print("Mean shape:", mean.shape)
print("Std shape:", std.shape)
print("Scaled shape:", X_scaled.shape)


X shape: (500, 20)
Mean shape: (20,)
Std shape: (20,)
Scaled shape: (500, 20)


## 22. Performance and Memory

Array memory depends on:

- number of elements
- data type

Typical sizes:

```text
float64 → 8 bytes per element
float32 → 4 bytes per element
int64   → 8 bytes per element
int32   → 4 bytes per element
```

Useful properties:

```python
a.nbytes
a.itemsize
```

For many Machine Learning workloads, `float32` can reduce memory usage substantially compared with `float64`.


In [24]:
a64 = np.zeros(1_000_000, dtype=np.float64)
a32 = np.zeros(1_000_000, dtype=np.float32)

print("float64 bytes:", a64.nbytes)
print("float32 bytes:", a32.nbytes)
print("float64 itemsize:", a64.itemsize)
print("float32 itemsize:", a32.itemsize)


float64 bytes: 8000000
float32 bytes: 4000000
float64 itemsize: 8
float32 itemsize: 4


# 23. Practical Bioinformatics Example — Gene Expression

Imagine a gene-expression matrix:

```text
Rows    → Patients
Columns → Genes
Values  → Expression levels
```

Suppose:

```text
100 patients × 1000 genes
```

We can use NumPy to calculate gene-level statistics, filter genes, normalize data, and select important features.


In [25]:
rng = np.random.default_rng(42)

expression = rng.normal(
    loc=10,
    scale=2,
    size=(100, 1000)
)

print("Shape:", expression.shape)


Shape: (100, 1000)


In [26]:
# Calculate mean expression for every gene
gene_means = expression.mean(axis=0)

# Calculate mean expression for every patient
patient_means = expression.mean(axis=1)

# Find the 10 genes with the highest mean expression
top_indices = np.argsort(gene_means)[-10:][::-1]

print("Gene means shape:", gene_means.shape)
print("Patient means shape:", patient_means.shape)
print("Top gene indices:", top_indices)
print("Top gene means:", gene_means[top_indices])


Gene means shape: (1000,)
Patient means shape: (100,)
Top gene indices: [688 563 230 368 169 273 479 962 770 299]
Top gene means: [10.69253155 10.54697155 10.51714685 10.50072333 10.49705066 10.49517612
 10.49512627 10.47518479 10.46746996 10.46691704]


In [27]:
# Filter genes whose mean expression is above 10
selected = expression[:, gene_means > 10]

print("Original shape:", expression.shape)
print("Filtered shape:", selected.shape)


Original shape: (100, 1000)
Filtered shape: (100, 489)


## 24. Missing Values in Gene Expression

Real datasets may contain missing measurements.

We can detect them with `np.isnan()` and use `np.nanmean()` to calculate statistics while ignoring NaN values.


In [28]:
expression_nan = expression.copy()

# Insert a few missing values
expression_nan[0, 0] = np.nan
expression_nan[10, 20] = np.nan
expression_nan[50, 100] = np.nan

print("Number of NaN values:", np.isnan(expression_nan).sum())

gene_means_nan = np.nanmean(expression_nan, axis=0)

print("First 5 NaN-aware gene means:", gene_means_nan[:5])


Number of NaN values: 3
First 5 NaN-aware gene means: [ 9.63275837 10.14450335 10.06886757  9.9984211  10.05736802]


# 25. Practical Machine Learning Example

A typical feature matrix has:

```text
Rows    → Samples
Columns → Features
```

For example:

```text
X.shape = (500, 20)
```

means 500 samples and 20 features.

A target vector may have:

```text
y.shape = (500,)
```


In [29]:
rng = np.random.default_rng(123)

X = rng.normal(size=(500, 20))
y = rng.integers(0, 2, size=500)

# Standardize each feature
mean = X.mean(axis=0)
std = X.std(axis=0)
std_safe = np.where(std == 0, 1, std)

X_scaled = (X - mean) / std_safe

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Scaled shape:", X_scaled.shape)
print("First feature mean:", X_scaled[:, 0].mean())
print("First feature std:", X_scaled[:, 0].std())


X shape: (500, 20)
y shape: (500,)
Scaled shape: (500, 20)
First feature mean: 5.684341886080802e-17
First feature std: 1.0


# 26. Common Mistakes

### Mistake 1 — Confusing `*` and `@`

```text
* → element-wise multiplication
@ → matrix multiplication
```

### Mistake 2 — Wrong axis

Ask:

```text
What does each row represent?
What does each column represent?
```

### Mistake 3 — Broadcasting mismatch

Check:

```python
array.shape
```

### Mistake 4 — Accidental shared memory

Use:

```python
a.copy()
```

when you need independent data.

### Mistake 5 — Ignoring NaN values

Use appropriate `np.nan*` functions.

### Mistake 6 — Unnecessary Python loops

Look for a vectorized NumPy operation first.


# 27. Mini Project — Gene Expression Analysis

Create a synthetic dataset with:

```text
200 patients
500 genes
```

Tasks:

1. Calculate the mean expression of every gene.
2. Find the 20 genes with the highest mean expression.
3. Calculate the mean expression of every patient.
4. Standardize each gene using z-score normalization.
5. Introduce several NaN values.
6. Recalculate gene means using `np.nanmean()`.
7. Filter genes using a mean-expression threshold.
8. Report the final matrix shape.


In [30]:
# Mini Project Solution

rng = np.random.default_rng(2026)

# Create synthetic gene-expression data
expression = rng.normal(
    loc=10,
    scale=2,
    size=(200, 500)
)

# 1. Mean expression for every gene
gene_means = expression.mean(axis=0)

# 2. Top 20 genes
top_20 = np.argsort(gene_means)[-20:][::-1]

# 3. Mean expression for every patient
patient_means = expression.mean(axis=1)

# 4. Z-score standardization per gene
gene_std = expression.std(axis=0)
gene_std_safe = np.where(gene_std == 0, 1, gene_std)

expression_z = (expression - gene_means) / gene_std_safe

# 5. Add missing values
expression_missing = expression.copy()
expression_missing[0, 0] = np.nan
expression_missing[10, 20] = np.nan
expression_missing[50, 100] = np.nan

# 6. NaN-aware gene means
gene_means_nan = np.nanmean(expression_missing, axis=0)

# 7. Filter genes
filtered = expression_missing[:, gene_means_nan > 10]

# 8. Report results
print("Original shape:", expression.shape)
print("Z-score shape:", expression_z.shape)
print("Patient means shape:", patient_means.shape)
print("Top 20 gene indices:", top_20)
print("Missing values:", np.isnan(expression_missing).sum())
print("Filtered shape:", filtered.shape)


Original shape: (200, 500)
Z-score shape: (200, 500)
Patient means shape: (200,)
Top 20 gene indices: [143 321 236 194 353 215 189 383 382 311  15 300 107 138  72 376 416 471
 274  65]
Missing values: 3
Filtered shape: (200, 249)


# 28. Exercises

### Exercise 1 — Advanced Indexing

Create a `5 × 5` matrix and select rows `0, 2, 4` and columns `1, 3`.

### Exercise 2 — Broadcasting

Create an array with shape `(4, 3)` and add a vector containing three values. Explain why broadcasting works.

### Exercise 3 — Axis

Create a matrix representing 10 patients × 5 genes. Calculate the mean expression for each gene and each patient.

### Exercise 4 — Normalization

Create a `100 × 10` feature matrix and perform feature-wise z-score standardization.

### Exercise 5 — Linear Algebra

Create two compatible matrices and compare:

```python
A * B
A @ B
```

Explain the difference.

### Exercise 6 — Missing Values

Create an array containing NaN values and compare:

```text
mean vs nanmean
median vs nanmedian
```

### Exercise 7 — Bioinformatics Challenge

Create a `100 × 1000` gene-expression matrix and find the 10 genes with the highest mean expression.


# 29. Final Concept Map

```text
Advanced Indexing
        ↓
Advanced Slicing
        ↓
Axis
        ↓
Broadcasting
        ↓
Vectorization
        ↓
Copy vs View
        ↓
Shape Manipulation
        ↓
Stacking / Splitting
        ↓
Missing Values
        ↓
Mathematical Functions
        ↓
Linear Algebra
        ↓
Random Simulation
        ↓
Normalization
        ↓
Performance / Memory
        ↓
Bioinformatics + Machine Learning
```

The most important conceptual connections are:

```text
axis + broadcasting + vectorization
```

and:

```text
vectors + matrices + matrix multiplication
```

Finally, develop the habit of checking `.shape` and identifying what rows and columns represent before performing operations.


# 30. Cheat Sheet

| Category | Function / Concept | Description |
|---|---|---|
| Indexing | `a[[...]]` | Fancy / integer indexing |
| Indexing | `a[mask]` | Boolean indexing |
| Slicing | `a[start:stop:step]` | Select a range |
| Axis | `axis=0` | Result for each column |
| Axis | `axis=1` | Result for each row |
| Broadcasting | `A + b` | Operate on compatible shapes |
| Vectorization | `A * 2` | Vectorized element-wise operation |
| Memory | `a.copy()` | Independent copy |
| Memory | `a.view()` | View sharing data when possible |
| Memory | `np.shares_memory()` | Check shared memory |
| Shape | `reshape()` | Change shape |
| Shape | `expand_dims()` | Add a dimension |
| Shape | `squeeze()` | Remove dimensions of size 1 |
| Shape | `transpose()` | Transpose an array |
| Shape | `swapaxes()` | Swap two axes |
| Shape | `moveaxis()` | Move an axis |
| Combine | `concatenate()` | Join along an existing axis |
| Combine | `stack()` | Join along a new axis |
| Combine | `vstack()` | Vertical stacking |
| Combine | `hstack()` | Horizontal stacking |
| Split | `split()` | Split an array |
| Split | `array_split()` | Split into sections |
| Missing | `np.isnan()` | Detect NaN values |
| Missing | `np.isinf()` | Detect infinite values |
| Missing | `np.isfinite()` | Detect finite values |
| Missing | `np.nanmean()` | Mean ignoring NaN |
| Math | `np.dot()` | Dot product |
| Linear Algebra | `@` | Matrix multiplication |
| Linear Algebra | `np.linalg.det()` | Determinant |
| Linear Algebra | `np.linalg.inv()` | Matrix inverse |
| Linear Algebra | `np.linalg.solve()` | Solve a linear system |
| Linear Algebra | `np.linalg.eig()` | Eigenvalues and eigenvectors |
| Linear Algebra | `np.linalg.norm()` | Vector / matrix norm |
| Random | `np.random.default_rng()` | Create a random generator |
| Random | `rng.random()` | Uniform random values |
| Random | `rng.integers()` | Random integers |
| Random | `rng.normal()` | Normal distribution |
| Data | Min-Max Scaling | Scale values to a fixed range |
| Data | Z-score | Standardize using mean and standard deviation |
| Performance | `a.nbytes` | Total array memory |
| Performance | `a.itemsize` | Bytes per element |


# 31. Golden Rules

1. **Always check `.shape`.**
2. `axis=0` → result for each column.
3. `axis=1` → result for each row.
4. `*` → element-wise multiplication.
5. `@` → matrix multiplication.
6. Check broadcasting compatibility before arithmetic.
7. Use `copy()` when independent data is required.
8. Prefer vectorization over unnecessary Python loops.
9. Use NaN-aware functions when missing values are present.
10. In Bioinformatics and Machine Learning, always know what rows and columns represent.


# End of Part 2

You have moved from basic NumPy syntax to **advanced numerical computing**.